version: '3'

services:
  mqtt_client:
    build: ./mqtt_client
    container_name: mqtt_client
    environment:
      - TZ=Europe/Prague
    #depends_on:
      #- influxdb

  #influxdb:
    #image: influxdb:2.0
    #container_name: influxdb
    #ports:
      #- "8086:8086"
    #environment:
      #- DOCKER_INFLUXDB_INIT_MODE=setup
      #- DOCKER_INFLUXDB_INIT_USERNAME=admin
      #- DOCKER_INFLUXDB_INIT_PASSWORD=supersecretpassword
      #- DOCKER_INFLUXDB_INIT_ORG=myorg
      #- DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      #- DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    #volumes:
      #- influxdb-data:/var/lib/influxdb2

#volumes:
  #influxdb-data:


